apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml


namespace: goapp

images:
- name: goapp
  newName: josealceu/argocd
  newTag: 841e1751133b235ed0753b4da87011965607c1e6
- name: gooapp
  newName: josealceu/argocd
  newTag: af028fbad48b1076913d1ce93304debf296beace
