apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml


namespace: goapp

images:
- name: goapp
  newName: josealceu/argocd
  newTag: b719e88b2eee1e28160126a9a4ae408ddc7ae47f
- name: gooapp
  newName: josealceu/argocd
  newTag: af028fbad48b1076913d1ce93304debf296beace
