apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml


namespace: goapp

images:
- name: goapp
  newName: goapp
  newTag: v1
- name: gooapp
  newName: josealceu/argocd
  newTag: af028fbad48b1076913d1ce93304debf296beace
