apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml


namespace: goapp

images:
- name: goapp
  newName: josealceu/argocd
  newTag: f17aa2b4cee7655ff16eb4617fda05087ad77e7b
- name: gooapp
  newName: josealceu/argocd
  newTag: af028fbad48b1076913d1ce93304debf296beace
