apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml


namespace: goapp

images:
- name: goapp
  newName: josealceu/argocd
  newTag: 6d1a06f3127abfe9d9b4b29ca06224347a603fb4
- name: gooapp
  newName: josealceu/argocd
  newTag: af028fbad48b1076913d1ce93304debf296beace
