name: CD3
on:
    push:
        branches: master
jobs:
  retrieve-secret:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Retrieve secret from Vault
        uses: hashicorp/vault-action@v2.7.3
        with:
            method: github
            url: https://vault.axonlab.com.br
            githubToken: ${{ secrets.TOKEN }}
            secrets: |
                    secret/production teste | TESTE
                    
      - name: Authentication DockerHub
        uses: docker/login-action@v2.1.0
        with:
          username: josealceu
          password: ${{secrets.DOCKER_PASSWORD }}

      - name: Build and tag Docker image
        run: |
            docker build --build-arg mysql_database=$TESTE
                     -t josealceu/argocd:latest.

      - name: Push Docker image to DockerHub
        run: |
            docker push josealceu/argocd:latest

      - name: Exibir a secret
        run: |
            cd k8s
            echo "Minha linda secret: $TESTE" >> text.txt
            cat text.txt
      - name: Push Git Commit
        run: |
                    git add .
                    git config --local user.email "action@github.com"
                    git config --local user.name "Deploy Action"
                    git commit -am "change image tag"
            
      - name: push
        uses: ad-m/github-push-action@master

            
            


                    
        
                    
