name: CD
on:
    push:
            branches: master
jobs:
  retrieve-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve secret from Vault
        uses: hashicorp/vault-action@v2.7.3
        with:
            method: github
            url: https://vault.axonlab.com.br
            githubToken: ${{ secrets.TOKEN }}
            secrets: |
                    secret/production teste | TESTE
                    
