name: CD
on:
    push:
            branches: master
jobs:
  retrieve-secret:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Retrieve secret from Vault
        uses: hashicorp/vault-action@v2.4.0
        with:
            method: jwt
            url: https://vault.axonlab.com.br
            role: deployment-processes-policy
            secrets: secret/data/apikeys/deploymentServer kv
            
      - name: Use secret from Vault
        run: |
          # This step has access to the secret retrieved above; see hashicorp/vault-action for more details.
                
