name: Minha Action do GitHub

on:
  push:
    branches:
      - master # Ajuste de acordo com a branch desejada

jobs:
  buscar-secret:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v2

    - name: Configurar o Vault GitHub Action
      uses: hashicorp/vault-action@v2.4.0
      with:
        url: https://vault.axonlab.com.br
        token: hvs.lrxWulp6MfC5RuadxJ8dSJ8a
        secrets: |
            secret/data/production teste | DEPLOYMENT_KEY
