name: CD3
on:
    push:
        branches: master
jobs:
  retrieve-secret:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Retrieve secret from Vault
        uses: hashicorp/vault-action@v2.7.3
        with:
            method: github
            url: https://vault.axonlab.com.br
            githubToken: ${{ secrets.TOKEN }}
            secrets: |
                    secret/production teste | MYSQL_DATABASE
      - name: Build image and push to docker hub
        uses: docker/build-push-action@v1.1.0
        with:
            build_args: mysql_database=$MYSQL_DATABASE
            username: josealceu
            password: ${{secrets.DOCKER_PASSWORD }}
            repository: josealceu/argocd
            tags: latest


            
            


                    
        
                    
