name: CD
on:
    push:
            branches: master
jobs:
  retrieve-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Retrieve secret from Vault
        uses: hashicorp/vault-action@v2.4.0
        with:
            url: https://vault.axonlab.com.br
            token: hvs.lrxWulp6MfC5RuadxJ8dSJ8a
            secrets: |
                    secret/data/production teste | DEPLOYMENT_KEY
