name: Minha Action do GitHub

on:
  push:
    branches:
      - main  # Ajuste de acordo com a branch desejada

jobs:
  buscar-secret:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v2

    - name: Configurar o Vault
      run: |
        # Configurar o Vault URL e token
        echo "https://vault.lindaocom.br/" > VAULT_ADDR
        echo "123456" > VAULT_TOKEN

    - name: Buscar a secret do Vault
      run: |
        # Utilize o CLI do Vault para buscar a secret desejada
        # Substitua "MINHA_SECRET" pelo nome do campo que você deseja buscar na secret
        teste=$(vault kv get -field=teste secret/production)

    - name: Exibir a secret
      run: |
        # Exibir a secret que foi buscada do Vault
        echo "Minha secret: $teste"

